# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EAS
    username: root
    password: ""

# ===============================
# = JPA configurations
# ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      # this is for lazy loading
      hibernate.enable_lazy_load_no_trans: true

# ===============================
# = Spring data rest configurations
# ===============================
  data:
    rest:
      base-path: /api

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: warn
    com.peng1m: debug
    com.springframework.web: info
    com.springframework.security: info